version: '3.8'

services:
  # MongoDB database
  mongodb:
    image: mongo:6.0
    container_name: auto-consult-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db

  # Frontend application
  frontend:
    build:
      context: ../apps/frontend
      dockerfile: Dockerfile
    container_name: auto-consult-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:3001

  # Backend application
  backend:
    build:
      context: ../apps/backend
      dockerfile: Dockerfile
    container_name: auto-consult-backend
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/auto-consult?authSource=admin
      - PORT=3001

volumes:
  mongodb_data: